// <auto-generated />
using System;
using IIT.Glid.Gestion_Formation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IIT.Glid.Gestion_Formation.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Etudiant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Payement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FormationID");

                    b.ToTable("Etudiant");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateInscription = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "ali",
                            Payement = true,
                            Prenom = "aydi",
                            Telephone = "112233"
                        });
                });

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Formateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<float>("Couts")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Formateur");
                });

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Formation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duree")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormateurID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Frais")
                        .HasColumnType("REAL");

                    b.Property<string>("Sujet")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FormateurID");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Voiture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marque")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Voitures");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Marque = "Polo",
                            Matricule = "128 TN 1589",
                            Modele = "6"
                        },
                        new
                        {
                            Id = 2L,
                            Marque = "Polo",
                            Matricule = "128 TN 1589",
                            Modele = "6"
                        });
                });

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Etudiant", b =>
                {
                    b.HasOne("IIT.Glid.Gestion_Formation.Domain.Formation", null)
                        .WithMany("Etudiants")
                        .HasForeignKey("FormationID");
                });

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Formation", b =>
                {
                    b.HasOne("IIT.Glid.Gestion_Formation.Domain.Formateur", "Formateur")
                        .WithMany()
                        .HasForeignKey("FormateurID");

                    b.Navigation("Formateur");
                });

            modelBuilder.Entity("IIT.Glid.Gestion_Formation.Domain.Formation", b =>
                {
                    b.Navigation("Etudiants");
                });
#pragma warning restore 612, 618
        }
    }
}
